### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by davidspek** [davidk/docker-slic3r-prusa3d#4]
I was just wondering if this docker based PrusaSlicer contains a GUI or if it is for command-line use only. I found a different docker for the regular Slic3r that uses SPICE to provide a GUI, although it is old (linked below). Ultimately, I thought it might be interesting to run PrusaSlicer in a docker environment with web access to the GUI, and then integrate this into OctoPrint somehow. 

https://hub.docker.com/r/kkessler/slic3r/

**Comment by davidk** [comment]
Hello there, thanks for the question!

The container's dependencies are setup to run PrusaSlicer in GUI mode by default.

The CLI mode is available for things like batch slicing, but that needs parameters passed to it. An example implementation is in this Github Action's entrypoint.sh: https://github.com/davidk/slic3r-action/blob/master/gcode/entrypoint.sh
