### ISSUE TITLE
Segmentation fault of prusa-slicer

### ISSUE THREAD

**Issue by ivanovp** [davidk/docker-slic3r-prusa3d#6]
Hi,

I've got a segmentation fault. I'm not sure what information do you need, this is what I see on output of console:
`
slic3r@c826cad81dbb:/Slic3r/slic3r-dist$ ./prusa-slicer 
No protocol specified
Segmentation fault (core dumped)
`

I'd run a 'strace' with prusa-slicer, but I'm newbie to docker.

Command on host OS, which is Arch Linux:
`
docker run -v /tmp/.X11-unix:/tmp/.X11-unix \
-v $PWD:/Slic3r/3d:z \
-v slic3rSettings:/home/slic3r \
-e DISPLAY=$DISPLAY \
--entrypoint=/bin/bash \
-it keyglitch/docker-slic3r-prusa3d
`

Thanks,
Peter

**Comment by davidk** [comment]
Hello,

I see this as well, running under an Ubuntu VM:

	slic3r@2e2f716dd43d:/Slic3r/slic3r-dist$ ./prusa-slicer 
	terminate called after throwing an instance of 'std::logic_error'
	  what():  basic_string::_S_construct null not valid
	Aborted (core dumped)
	slic3r@2e2f716dd43d:/Slic3r/slic3r-dist$ 

Copying the built distribution out of the container works, so this is an issue with how the container is constructed. I'll be checking this out in more detail to see where the problem lies, thanks for reporting this behavior!

**Comment by ivanovp** [comment]
Hi,

I think the "No protocol error" is related to Xorg permissions. I can give permission to a different user with this command, but I'm not sure if 'slic3r' is a localuser:
`xhost +SI:localuser:slic3r`

I have not tried it yet.

Regards,
Peter

**Comment by davidk** [comment]
Hi Peter,

I've updated the Dockerfile and pushed a new image to the Docker Hub that should patch over the segfault. PrusaSlicer expects the USER environmental variable to be set; in this case it was not, causing a crash.

The container now sets this in the build. At your earliest convenience, please pull down the rebuilt image and give it another try.

**Comment by ivanovp** [comment]
Hi David,

I updated the image, executed 'xhost local:root'. Now I get different error message:

`libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
The program 'prusa-slicer' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadContext'.
  (Details: serial 318 error_code 158 request_code 151 minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)`

Nothing is displayed on screen, but program execution is not aborted. I had to kill it with -9 switch.

Regards,
Peter

**Comment by davidk** [comment]
Hi Peter,

I tried, but i'm unable to reproduce the error locally with an Arch Linux installation in a VM -- PrusaSlicer launches and displays its GUI. Without being able to reproduce locally, my best guess is a conflict within the graphics driver configuration (based on the first two lines of errors).

It may help to run the container with `LIBGL_DEBUG=verbose` set to get some more visibility into the issue:

```
docker run -v /tmp/.X11-unix:/tmp/.X11-unix \
-v $PWD:/Slic3r/3d:z \
-v slic3rSettings:/home/slic3r \
-e DISPLAY=$DISPLAY \
-e LIBGL_DEBUG=verbose \
> --rm keyglitch/docker-slic3r-prusa3d
Gtk-Message: Failed to load module "canberra-gtk-module"
libGL: screen 0 does not appear to be DRI2 capable
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/tls/swrast_dri.so
libGL: OpenDriver: trying /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so
libGL: Can't open configuration file /home/slic3r/.drirc: No such file or directory.
libGL: Can't open configuration file /home/slic3r/.drirc: No such file or directory
```
