### ISSUE TITLE
Noob need help

### ISSUE THREAD

**Issue by roessi** [davidk/docker-slic3r-prusa3d#7]
Hi,
First of all THX for your work!
Im an absolut docker noob, but i m able to install other containers like Octoprint,...
So i tried to download and run your Prusa slicer container.
Download worked well, but when i run it, and right away it bring the message that the container stopps.
May you have some screenshots of the advanced settings i can follow. 😁

thx a lot

**Comment by davidk** [comment]
Hi,
If you're using Fedora or Ubuntu, after installing docker you should be able to run the following to start the container:

    docker run -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $PWD:/Slic3r/3d:z \
    -v slic3rSettings:/home/slic3r \
    -e DISPLAY=$DISPLAY \
    --rm keyglitch/docker-slic3r-prusa3d

There isn't any other configuration required, aside from a workaround for X permission errors (run `xhost local:root` if that happens).

**Comment by roessi** [comment]
Hi,
This is my problem i have no command line. In Synology Docker there is only the download and a Start with brings me to an GUI with some options.
![06612298-FF79-4689-A056-8EDA47533A93](https://user-images.githubusercontent.com/45541282/103854966-ee288b00-50b1-11eb-9c44-03d4e8d5f816.jpeg)

**Comment by davidk** [comment]
Synology's Docker limits what can be done for this container, but it is possible to slice on the command-line, similar to this:

    docker run -v $PWD:/Slic3r/3d:z \
    -v slic3rSettings:/home/slic3r \
    keyglitch/docker-slic3r-prusa3d \
    -g -s /Slic3r/3d/pi4-fan.stl

    10 => Processing triangulated mesh
    20 => Generating perimeters
    70 => Infilling layers
    30 => Preparing infill
    88 => Generating skirt
    90 => Exporting G-code to /Slic3r/3d/pi4-fan.gcode
    Slicing result exported to /Slic3r/3d/pi4-fan.gcode
    10 => Processing triangulated mesh
    20 => Generating perimeters
    70 => Infilling layers
    30 => Preparing infill
    88 => Generating skirt
    90 => Exporting G-code to /Slic3r/3d/pi4-fan.gcode
    Slicing result exported to /Slic3r/3d/pi4-fan.gcode

Using this container with Synology's Docker wouldn't be a great experience, but the following might work, if you still want to slice using the command-line equivalent above:

    - Advanced Settings:
        - Add Folder [File/Folder -> Mount Path]
            - /volume1/docker/slic3r/settings -> /home/slic3r
            - /volume1/docker/slic3r/stls -> /Slic3r/3d
        - Environment:
            - Command: "-g -s /Slic3r/3d/file_to_slice.stl"

Each STL would have to be uploaded to /volume1/docker/slic3r/stls (the folder from above) as `file_to_slice.stl`. Running
the container should slice the file as above and return the gcode into the `stls` folder.
